package com.github.sib_energy_craft.sec_common.screen.property;

import io.netty.buffer.ByteBuf;
import net.minecraft.network.codec.StreamCodec;
import org.jetbrains.annotations.NotNull;

import java.util.function.Supplier;

/**
 * Dynamic typed screen property
 *
 * @author sibmaks
 * @since 0.0.7-1.21.4
 */
public record DynamicTypedScreenProperty<B extends ByteBuf, T>(
        int id,
        @NotNull StreamCodec<B, T> codec,
        @NotNull Supplier<T> valueSupplier
) implements TypedScreenProperty<B, T> {

    /**
     * Get property value.<br/>
     * Property generated by calling {@link DynamicTypedScreenProperty#valueSupplier} each time
     *
     * @return property value
     */
    @Override
    public T value() {
        return valueSupplier.get();
    }

}
